### ISSUE TITLE
WiimoteHook Download link broken

### ISSUE THREAD

**Issue by CassiusOtho** [epigramx/WiimoteHook#1]
When I go to https://epigramx.github.io/WiimoteHook/ and click on the "WiimoteHook_20180616_080042_beta.zip" link, nothing happens. It seems like the link is broken or not working. Could you please update this so that the link works?

**Comment by epigramx** [comment]
It seems to still work, google drive probably had a temporary hiccup. Or you didn't wait for ~3-4 seconds (because it always has that delay).

**Comment by CassiusOtho** [comment]
Chrome browser was the cause of the problem strangely enough. I Tried downloading with edge browser and it worked. Thank you for your response, and for all your hard work on this project.
